import { DataSource } from 'typeorm';
import * as bcrypt from 'bcryptjs';
import * as dotenv from 'dotenv';
import { User } from './src/user/user.entity';
import { Hospital } from './src/hospital/hospital.entity';
import { Theatre } from './src/theatre/theatre.entity';
import { Ambulance } from './src/ambulance/ambulance.entity';
import { Equipment } from './src/common/types';
import {
  UserRole,
  UserStatus,
  Gender,
  BloodGroup,
  AmbulanceType,
  AmbulanceStatus,
  TheatreType,
  TheatreStatus,
  SterilityClass,
  MedicalSpecialty,
  HospitalType,
} from './src/common/enums';

dotenv.config();

const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DATABASE_HOST || 'localhost',
  port: parseInt(process.env.DATABASE_PORT || '5432', 10),
  username: process.env.DATABASE_USER || 'postgres',
  password: process.env.DATABASE_PASSWORD || 'postgres',
  database: process.env.DATABASE_NAME || 'ambulance_theatre_dev',
  entities: [User, Hospital, Theatre, Ambulance],
  synchronize: true,
});

async function seed() {
  console.log('Connecting to database...');
  await AppDataSource.initialize();
  console.log('Database connected.');

  const userRepo = AppDataSource.getRepository(User);
  const hospitalRepo = AppDataSource.getRepository(Hospital);
  const theatreRepo = AppDataSource.getRepository(Theatre);
  const ambulanceRepo = AppDataSource.getRepository(Ambulance);

  const hashedPassword = await bcrypt.hash('Password123!', 10);
  const point = (lat: number, lng: number) => ({ type: 'Point', coordinates: [lng, lat] });

  // Clean existing records across related tables.
  await AppDataSource.query(`
    DO $$
    DECLARE
      t text;
    BEGIN
      FOREACH t IN ARRAY ARRAY[
        'emergency_requests',
        'theatre_bookings',
        'bookings',
        'notifications',
        'ambulances',
        'theatres',
        'hospitals',
        'users'
      ]
      LOOP
        IF to_regclass(t) IS NOT NULL THEN
          EXECUTE format('TRUNCATE TABLE %I RESTART IDENTITY CASCADE', t);
        END IF;
      END LOOP;
    END $$;
  `);

  console.log('Creating users...');
  const users = await userRepo.save([
    userRepo.create({
      email: 'admin@ambulance-theatre.com',
      phone_number: '+2348011111001',
      password: hashedPassword,
      name: 'Platform Admin',
      role: UserRole.SYSTEM_ADMIN,
      status: UserStatus.ACTIVE,
      gender: Gender.MALE,
      is_email_verified: true,
      is_phone_verified: true,
    }),
    userRepo.create({
      email: 'doctor.lagos@ambulance-theatre.com',
      phone_number: '+2348011111002',
      password: hashedPassword,
      name: 'Dr. Tolu Adeyemi',
      role: UserRole.DOCTOR,
      status: UserStatus.ACTIVE,
      gender: Gender.FEMALE,
      is_email_verified: true,
      is_phone_verified: true,
    }),
    userRepo.create({
      email: 'driver.lagos@ambulance-theatre.com',
      phone_number: '+2348011111003',
      password: hashedPassword,
      name: 'Seyi Balogun',
      role: UserRole.DRIVER,
      status: UserStatus.ACTIVE,
      gender: Gender.MALE,
      driver_license_number: 'LAG-DRV-23881',
      license_expiry_date: new Date('2028-12-31'),
      is_email_verified: true,
      is_phone_verified: true,
    }),
    userRepo.create({
      email: 'driver.ibadan@ambulance-theatre.com',
      phone_number: '+2348011111004',
      password: hashedPassword,
      name: 'Ridwan Afolabi',
      role: UserRole.DRIVER,
      status: UserStatus.ACTIVE,
      gender: Gender.MALE,
      driver_license_number: 'IBA-DRV-99231',
      license_expiry_date: new Date('2029-06-30'),
      is_email_verified: true,
      is_phone_verified: true,
    }),
    userRepo.create({
      email: 'patient@ambulance-theatre.com',
      phone_number: '+2348011111005',
      password: hashedPassword,
      name: 'Kemi Olanrewaju',
      role: UserRole.PATIENT,
      status: UserStatus.ACTIVE,
      gender: Gender.FEMALE,
      blood_group: BloodGroup.O_POSITIVE,
      date_of_birth: new Date('1992-08-11'),
      latitude: 6.5244,
      longitude: 3.3792,
      is_email_verified: true,
      is_phone_verified: true,
    }),
  ]);

    const lagosDriver = users.find((u) => u.email === 'driver.lagos@ambulance-theatre.com')!;
  const ibadanDriver = users.find((u) => u.email === 'driver.ibadan@ambulance-theatre.com')!;

  console.log('Creating hospitals (major Lagos + Ibadan)...');
  // Coordinates researched from Wikidata hospital entries.
  const hospitals = await hospitalRepo.save([
    {
      name: 'Lagos University Teaching Hospital (LUTH)',
      registration_number: 'NG-LAG-LUTH-001',
      phone_numbers: ['+234-807-059-1395'],
      email: 'info@luth.gov.ng',
      address: {
        street: 'Ishaga Road, Idi-Araba',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101245',
        full_address: 'Idi-Araba, Surulere, Lagos',
      },
      latitude: 6.5176,
      longitude: 3.3537,
      location: point(6.5176, 3.3537),
      type: HospitalType.TEACHING,
      total_beds: 761,
      available_beds: 430,
      icu_beds: 45,
      emergency_beds: 90,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.NEUROLOGY, MedicalSpecialty.GENERAL_SURGERY],
      rating: 4.5,
      total_reviews: 1842,
    } as any,
    {
      name: 'Lagos State University Teaching Hospital (LASUTH)',
      registration_number: 'NG-LAG-LASUTH-002',
      phone_numbers: ['+234-909-148-1560'],
      email: 'info@lasuth.org.ng',
      address: {
        street: 'Oba Akinjobi Way, Ikeja',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101233',
        full_address: 'Oba Akinjobi Way, Ikeja GRA, Lagos',
      },
      latitude: 6.5904,
      longitude: 3.3423,
      location: point(6.5904, 3.3423),
      type: HospitalType.TEACHING,
      total_beds: 500,
      available_beds: 280,
      icu_beds: 35,
      emergency_beds: 65,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.EMERGENCY_MEDICINE, MedicalSpecialty.PEDIATRICS, MedicalSpecialty.ORTHOPEDICS],
      rating: 4.4,
      total_reviews: 1210,
    } as any,
    {
      name: 'Federal Medical Centre, Ebute Metta',
      registration_number: 'NG-LAG-FMCEM-003',
      phone_numbers: ['+234-1-774-6000'],
      email: 'info@fmceb.org',
      address: {
        street: '2 Ondo Street, Ebute Metta',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101212',
        full_address: '2 Ondo Street, Ebute Metta, Lagos',
      },
      latitude: 6.485083,
      longitude: 3.380182,
      location: point(6.485083, 3.380182),
      type: HospitalType.PUBLIC,
      total_beds: 200,
      available_beds: 126,
      icu_beds: 18,
      emergency_beds: 30,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.OBSTETRICS],
      rating: 4.2,
      total_reviews: 640,
    } as any,
    {
      name: 'Lagos Island General Hospital (Odan)',
      registration_number: 'NG-LAG-ODAN-004',
      phone_numbers: ['+234-815-061-0106'],
      email: 'admin@lagosislandgh.ng',
      address: {
        street: '216 Broad Street, Odan',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '100001',
        full_address: '216 Broad Street, Lagos Island, Lagos',
      },
      latitude: 6.4475,
      longitude: 3.3971,
      location: point(6.4475, 3.3971),
      type: HospitalType.PUBLIC,
      total_beds: 180,
      available_beds: 93,
      icu_beds: 12,
      emergency_beds: 25,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.EMERGENCY_MEDICINE, MedicalSpecialty.OBSTETRICS, MedicalSpecialty.GYNECOLOGY],
      rating: 4.1,
      total_reviews: 520,
    } as any,
    {
      name: 'National Orthopaedic Hospital, Igbobi',
      registration_number: 'NG-LAG-NOHI-005',
      phone_numbers: ['+234-706-640-4598'],
      email: 'info@nohlagos.gov.ng',
      address: {
        street: '120/124 Ikorodu Road, Igbobi',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '100233',
        full_address: '120/124 Ikorodu Road, Igbobi, Lagos',
      },
      latitude: 6.531,
      longitude: 3.3712,
      location: point(6.531, 3.3712),
      type: HospitalType.SPECIALTY,
      total_beds: 450,
      available_beds: 260,
      icu_beds: 20,
      emergency_beds: 40,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.ORTHOPEDICS, MedicalSpecialty.GENERAL_SURGERY],
      rating: 4.3,
      total_reviews: 790,
    } as any,
    {
      name: 'Gbagada General Hospital',
      registration_number: 'NG-LAG-GBAGADA-006',
      phone_numbers: ['+234-905-395-3306'],
      email: 'info@gbagada-gh.ng',
      address: {
        street: '1 Hospital Road, Gbagada',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '100234',
        full_address: '1 Hospital Road, Gbagada, Lagos',
      },
      latitude: 6.552561,
      longitude: 3.3871,
      location: point(6.552561, 3.3871),
      type: HospitalType.PUBLIC,
      total_beds: 118,
      available_beds: 64,
      icu_beds: 10,
      emergency_beds: 20,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.EMERGENCY_MEDICINE, MedicalSpecialty.PEDIATRICS],
      rating: 4.0,
      total_reviews: 430,
    } as any,
    {
      name: 'Reddington Hospital, Victoria Island',
      registration_number: 'NG-LAG-REDDINGTON-007',
      phone_numbers: ['+234-916-535-9769'],
      email: 'care@reddingtonhospital.com',
      address: {
        street: '12 Idowu Martins Street, Victoria Island',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101241',
        full_address: '12 Idowu Martins Street, Victoria Island, Lagos',
      },
      latitude: 6.4329,
      longitude: 3.4204,
      location: point(6.4329, 3.4204),
      type: HospitalType.PRIVATE,
      total_beds: 120,
      available_beds: 68,
      icu_beds: 14,
      emergency_beds: 22,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.NEUROLOGY, MedicalSpecialty.RADIOLOGY],
      rating: 4.4,
      total_reviews: 870,
    } as any,
    {
      name: 'General Hospital Apapa',
      registration_number: 'NG-LAG-APAPA-008',
      phone_numbers: ['+234-903-111-0077'],
      email: 'info@ghapapa.ng',
      address: {
        street: 'Abraham Adesanya Road, Apapa',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '102272',
        full_address: 'Abraham Adesanya Road, Apapa, Lagos',
      },
      latitude: 6.4419,
      longitude: 3.3688,
      location: point(6.4419, 3.3688),
      type: HospitalType.PUBLIC,
      total_beds: 130,
      available_beds: 73,
      icu_beds: 10,
      emergency_beds: 20,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.OBSTETRICS, MedicalSpecialty.PEDIATRICS, MedicalSpecialty.GENERAL_SURGERY],
      rating: 4.0,
      total_reviews: 320,
    } as any,
    {
      name: 'St. Nicholas Hospital',
      registration_number: 'NG-LAG-STNICH-009',
      phone_numbers: ['+234-201-280-0823'],
      email: 'care@stnicholashospital.ng',
      address: {
        street: '57 Campbell Street, Lagos Island',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '100221',
        full_address: '57 Campbell Street, Lagos Island, Lagos',
      },
      latitude: 6.4492,
      longitude: 3.3976,
      location: point(6.4492, 3.3976),
      type: HospitalType.PRIVATE,
      total_beds: 140,
      available_beds: 76,
      icu_beds: 12,
      emergency_beds: 18,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.NEUROLOGY, MedicalSpecialty.ONCOLOGY, MedicalSpecialty.UROLOGY],
      rating: 4.3,
      total_reviews: 540,
    } as any,
    {
      name: 'Iwosan Lagoon Hospital - Ikoyi',
      registration_number: 'NG-LAG-LAGOON-IKO-010',
      phone_numbers: ['+234-708-060-9000'],
      email: 'ikoyi@lagoonhospitals.com',
      address: {
        street: '17B Bourdillon Road, Ikoyi',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101233',
        full_address: '17B Bourdillon Road, Ikoyi, Lagos',
      },
      latitude: 6.4459,
      longitude: 3.4374,
      location: point(6.4459, 3.4374),
      type: HospitalType.PRIVATE,
      total_beds: 100,
      available_beds: 58,
      icu_beds: 10,
      emergency_beds: 15,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.PEDIATRICS],
      rating: 4.5,
      total_reviews: 610,
    } as any,
    {
      name: 'Iwosan Lagoon Hospital - Ikeja',
      registration_number: 'NG-LAG-LAGOON-IKJ-011',
      phone_numbers: ['+234-708-060-9000'],
      email: 'ikeja@lagoonhospitals.com',
      address: {
        street: '91 Obafemi Awolowo Way, Ikeja',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101233',
        full_address: '91 Obafemi Awolowo Way, Ikeja, Lagos',
      },
      latitude: 6.6043,
      longitude: 3.3457,
      location: point(6.6043, 3.3457),
      type: HospitalType.PRIVATE,
      total_beds: 95,
      available_beds: 52,
      icu_beds: 9,
      emergency_beds: 14,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.OBSTETRICS, MedicalSpecialty.PEDIATRICS, MedicalSpecialty.GENERAL_SURGERY],
      rating: 4.4,
      total_reviews: 380,
    } as any,
    {
      name: 'Eko Hospital - Ikeja',
      registration_number: 'NG-LAG-EKO-012',
      phone_numbers: ['+234-127-16997'],
      email: 'info@ekohospital.com',
      address: {
        street: '31 Mobolaji Bank Anthony Way, Opebi',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101233',
        full_address: '31 Mobolaji Bank Anthony Way, Opebi, Ikeja, Lagos',
      },
      latitude: 6.5878,
      longitude: 3.3576,
      location: point(6.5878, 3.3576),
      type: HospitalType.PRIVATE,
      total_beds: 132,
      available_beds: 74,
      icu_beds: 12,
      emergency_beds: 20,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.RADIOLOGY, MedicalSpecialty.ENT],
      rating: 4.3,
      total_reviews: 590,
    } as any,
    {
      name: 'Evercare Hospital, Lekki',
      registration_number: 'NG-LAG-EVERCARE-013',
      phone_numbers: ['+234-813-985-0710'],
      email: 'care@evercare.ng',
      address: {
        street: '1 Admiralty Way, Lekki Phase 1',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '106104',
        full_address: '1 Admiralty Way, Lekki Phase 1, Lagos',
      },
      latitude: 6.4377,
      longitude: 3.4571,
      location: point(6.4377, 3.4571),
      type: HospitalType.PRIVATE,
      total_beds: 165,
      available_beds: 91,
      icu_beds: 18,
      emergency_beds: 26,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.ONCOLOGY, MedicalSpecialty.NEUROLOGY],
      rating: 4.6,
      total_reviews: 670,
    } as any,
    {
      name: 'Duchess International Hospital',
      registration_number: 'NG-LAG-DUCHESS-014',
      phone_numbers: ['+234-201-640-1700'],
      email: 'info@duchesshospital.com',
      address: {
        street: '22A Joel Ogunnaike Street, Ikeja GRA',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '101233',
        full_address: '22A Joel Ogunnaike Street, Ikeja GRA, Lagos',
      },
      latitude: 6.5856,
      longitude: 3.3524,
      location: point(6.5856, 3.3524),
      type: HospitalType.PRIVATE,
      total_beds: 100,
      available_beds: 57,
      icu_beds: 11,
      emergency_beds: 17,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.RADIOLOGY],
      rating: 4.5,
      total_reviews: 420,
    } as any,
    {
      name: 'R-Jolad Plus Multi Specialist Hospital',
      registration_number: 'NG-LAG-RJOLAD-015',
      phone_numbers: ['+234-817-926-5691'],
      email: 'care@rjoladplus.ng',
      address: {
        street: '14 Safuratu Sekoni Street, Abule Okuta, Gbagada',
        city: 'Lagos',
        state: 'Lagos',
        country: 'Nigeria',
        postal_code: '100242',
        full_address: '14 Safuratu Sekoni Street, Abule Okuta, Gbagada, Lagos',
      },
      latitude: 6.5484,
      longitude: 3.3923,
      location: point(6.5484, 3.3923),
      type: HospitalType.PRIVATE,
      total_beds: 90,
      available_beds: 50,
      icu_beds: 8,
      emergency_beds: 13,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.PEDIATRICS, MedicalSpecialty.OBSTETRICS],
      rating: 4.2,
      total_reviews: 260,
    } as any,
    {
      name: 'University College Hospital (UCH), Ibadan',
      registration_number: 'NG-IBA-UCH-008',
      phone_numbers: ['+234-813-173-3447'],
      email: 'info@uch-ibadan.org.ng',
      address: {
        street: 'Queen Elizabeth II Road',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200212',
        full_address: 'Queen Elizabeth II Road, Agodi, Ibadan, Oyo State',
      },
      latitude: 7.4019,
      longitude: 3.9021,
      location: point(7.4019, 3.9021),
      type: HospitalType.TEACHING,
      total_beds: 1000,
      available_beds: 560,
      icu_beds: 52,
      emergency_beds: 110,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.ORTHOPEDICS, MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.OBSTETRICS],
      rating: 4.6,
      total_reviews: 1630,
    } as any,
    {
      name: 'Adeoyo Maternity Teaching Hospital, Ibadan',
      registration_number: 'NG-IBA-ADEOYO-009',
      phone_numbers: ['+234-704-573-3430'],
      email: 'info@adeoyomth.ng',
      address: {
        street: 'Yemetu Street',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200253',
        full_address: 'Yemetu Street, Ibadan',
      },
      latitude: 7.3871,
      longitude: 3.9025,
      location: point(7.3871, 3.9025),
      type: HospitalType.TEACHING,
      total_beds: 250,
      available_beds: 142,
      icu_beds: 16,
      emergency_beds: 28,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.OBSTETRICS, MedicalSpecialty.GYNECOLOGY, MedicalSpecialty.PEDIATRICS],
      rating: 4.1,
      total_reviews: 410,
    } as any,
    {
      name: 'Ring Road Specialist Hospital Complex, Ibadan',
      registration_number: 'NG-IBA-RINGROAD-010',
      phone_numbers: ['+234-803-803-3372'],
      email: 'admin@ringroadspecialist.ng',
      address: {
        street: 'Oluyole, Ring Road',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200273',
        full_address: 'Oluyole, Ring Road, Ibadan',
      },
      latitude: 7.351,
      longitude: 3.8624,
      location: point(7.351, 3.8624),
      type: HospitalType.SPECIALTY,
      total_beds: 140,
      available_beds: 82,
      icu_beds: 10,
      emergency_beds: 18,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.ORTHOPEDICS],
      rating: 4.0,
      total_reviews: 300,
    } as any,
    {
      name: 'Adeoyo State Hospital, Ibadan',
      registration_number: 'NG-IBA-ADEOYO-STATE-011',
      phone_numbers: ['+234-805-623-8599'],
      email: 'info@adeoyostatehospital.ng',
      address: {
        street: 'Ring Road / Oluyole',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200273',
        full_address: 'Ring Road / Oluyole, Ibadan',
      },
      latitude: 7.3506,
      longitude: 3.8629,
      location: point(7.3506, 3.8629),
      type: HospitalType.PUBLIC,
      total_beds: 180,
      available_beds: 102,
      icu_beds: 10,
      emergency_beds: 22,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.OBSTETRICS],
      rating: 4.1,
      total_reviews: 260,
    } as any,
    {
      name: 'Jericho Specialist Hospital, Ibadan',
      registration_number: 'NG-IBA-JERICHO-012',
      phone_numbers: ['+234-915-566-5146'],
      email: 'care@jerichospecialist.ng',
      address: {
        street: 'Magazine Road, Jericho',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200284',
        full_address: 'Magazine Road, Jericho, Ibadan',
      },
      latitude: 7.3969,
      longitude: 3.8707,
      location: point(7.3969, 3.8707),
      type: HospitalType.SPECIALTY,
      total_beds: 90,
      available_beds: 50,
      icu_beds: 6,
      emergency_beds: 14,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.ORTHOPEDICS, MedicalSpecialty.GENERAL_SURGERY],
      rating: 4.0,
      total_reviews: 185,
    } as any,
    {
      name: 'Government Chest Hospital, Ibadan',
      registration_number: 'NG-IBA-CHEST-013',
      phone_numbers: ['+234-705-552-2891'],
      email: 'info@chesthospitalibadan.ng',
      address: {
        street: 'Sabo-Onireke Road, Jericho',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200284',
        full_address: 'Sabo-Onireke Road, Jericho, Ibadan',
      },
      latitude: 7.3946,
      longitude: 3.8721,
      location: point(7.3946, 3.8721),
      type: HospitalType.SPECIALTY,
      total_beds: 70,
      available_beds: 39,
      icu_beds: 4,
      emergency_beds: 10,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.EMERGENCY_MEDICINE, MedicalSpecialty.GENERAL_SURGERY],
      rating: 3.9,
      total_reviews: 140,
    } as any,
    {
      name: "Oni Memorial Children's Hospital, Ibadan",
      registration_number: 'NG-IBA-ONI-014',
      phone_numbers: ['+234-000-000-0000'],
      email: 'care@onimemorial.ng',
      address: {
        street: 'MKO Abiola Way, Oluyole',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200273',
        full_address: 'MKO Abiola Way, Oluyole, Ibadan',
      },
      latitude: 7.3627,
      longitude: 3.8621,
      location: point(7.3627, 3.8621),
      type: HospitalType.SPECIALTY,
      total_beds: 80,
      available_beds: 46,
      icu_beds: 5,
      emergency_beds: 12,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.PEDIATRICS, MedicalSpecialty.OBSTETRICS],
      rating: 4.0,
      total_reviews: 170,
    } as any,
    {
      name: 'Ibadan Central Hospital',
      registration_number: 'NG-IBA-CENTRAL-015',
      phone_numbers: ['+234-703-363-5258'],
      email: 'info@ibadancentralhospital.ng',
      address: {
        street: '72 Ososami Road, New GRA',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200285',
        full_address: '72 Ososami Road, New GRA, Ibadan',
      },
      latitude: 7.3637,
      longitude: 3.8742,
      location: point(7.3637, 3.8742),
      type: HospitalType.PRIVATE,
      total_beds: 110,
      available_beds: 61,
      icu_beds: 8,
      emergency_beds: 15,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.OBSTETRICS, MedicalSpecialty.GYNECOLOGY, MedicalSpecialty.PEDIATRICS],
      rating: 4.1,
      total_reviews: 210,
    } as any,
    {
      name: 'Molly Specialist Hospital, Ibadan',
      registration_number: 'NG-IBA-MOLLY-016',
      phone_numbers: ['+234-818-886-6559'],
      email: 'care@mollyspecialist.ng',
      address: {
        street: 'Idi Ape Road',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200285',
        full_address: 'Idi Ape Road, Ibadan',
      },
      latitude: 7.4017,
      longitude: 3.9259,
      location: point(7.4017, 3.9259),
      type: HospitalType.SPECIALTY,
      total_beds: 130,
      available_beds: 72,
      icu_beds: 9,
      emergency_beds: 16,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.ORTHOPEDICS, MedicalSpecialty.NEUROLOGY],
      rating: 4.2,
      total_reviews: 240,
    } as any,
    {
      name: 'Jolamade Specialist Hospital (Avon Healthcare), Ibadan',
      registration_number: 'NG-IBA-JOLAMADE-017',
      phone_numbers: ['+234-802-324-7319'],
      email: 'admin@jolamadehospital.ng',
      address: {
        street: 'Salami Somade Estate, Agodi GRA',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200212',
        full_address: 'Salami Somade Estate, Agodi GRA, Ibadan',
      },
      latitude: 7.42,
      longitude: 3.9335,
      location: point(7.42, 3.9335),
      type: HospitalType.PRIVATE,
      total_beds: 95,
      available_beds: 54,
      icu_beds: 7,
      emergency_beds: 14,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.OBSTETRICS],
      rating: 4.0,
      total_reviews: 150,
    } as any,
    {
      name: 'Best Western Hospital, Ibadan',
      registration_number: 'NG-IBA-BESTWEST-018',
      phone_numbers: ['+234-814-585-5328'],
      email: 'care@bestwesternhospital.ng',
      address: {
        street: '2 Oyebanji Street, Bashorun',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200213',
        full_address: '2 Oyebanji Street, off Bashorun Market, Ibadan',
      },
      latitude: 7.4164,
      longitude: 3.9334,
      location: point(7.4164, 3.9334),
      type: HospitalType.PRIVATE,
      total_beds: 100,
      available_beds: 55,
      icu_beds: 7,
      emergency_beds: 14,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.CARDIOLOGY, MedicalSpecialty.EMERGENCY_MEDICINE],
      rating: 4.0,
      total_reviews: 165,
    } as any,
    {
      name: "St. Mary's General Hospital, Eleta, Ibadan",
      registration_number: 'NG-IBA-STMARY-019',
      phone_numbers: ['+234-805-273-5687'],
      email: 'info@stmaryseleta.ng',
      address: {
        street: 'Eleta',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200281',
        full_address: 'Eleta, Ibadan',
      },
      latitude: 7.3552,
      longitude: 3.9115,
      location: point(7.3552, 3.9115),
      type: HospitalType.PRIVATE,
      total_beds: 85,
      available_beds: 49,
      icu_beds: 5,
      emergency_beds: 11,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.GYNECOLOGY],
      rating: 3.9,
      total_reviews: 132,
    } as any,
    {
      name: 'Zenith Care Hospital, Ibadan',
      registration_number: 'NG-IBA-ZENITH-020',
      phone_numbers: ['+234-706-671-7822'],
      email: 'care@zenithcarehospital.ng',
      address: {
        street: '126 Alaafin Avenue Extension, Oluyole',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200273',
        full_address: '126 Alaafin Avenue Extension, Oluyole, Ibadan',
      },
      latitude: 7.3651,
      longitude: 3.8418,
      location: point(7.3651, 3.8418),
      type: HospitalType.PRIVATE,
      total_beds: 90,
      available_beds: 53,
      icu_beds: 6,
      emergency_beds: 12,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.OBSTETRICS, MedicalSpecialty.GYNECOLOGY, MedicalSpecialty.GENERAL_SURGERY],
      rating: 4.0,
      total_reviews: 120,
    } as any,
    {
      name: 'Military Hospital (2 Division), Ibadan',
      registration_number: 'NG-IBA-MIL-021',
      phone_numbers: ['+234-000-000-0001'],
      email: 'admin@2divisionmedical.ng',
      address: {
        street: 'Cantonment, Alaka/Ojoo',
        city: 'Ibadan',
        state: 'Oyo',
        country: 'Nigeria',
        postal_code: '200001',
        full_address: '2 Division Cantonment, Alaka/Ojoo, Ibadan',
      },
      latitude: 7.4703,
      longitude: 3.9259,
      location: point(7.4703, 3.9259),
      type: HospitalType.PUBLIC,
      total_beds: 120,
      available_beds: 70,
      icu_beds: 8,
      emergency_beds: 18,
      has_emergency: true,
      has_icu: true,
      has_ambulance_service: true,
      specialties: [MedicalSpecialty.GENERAL_SURGERY, MedicalSpecialty.EMERGENCY_MEDICINE],
      rating: 4.1,
      total_reviews: 95,
    } as any,
  ]);

  console.log('Creating theatres...');
  for (const hosp of hospitals) {
    await theatreRepo.save([
      theatreRepo.create({
        hospital_id: hosp.id,
        name: `${hosp.name} - General Theatre A`,
        type: TheatreType.GENERAL,
        specialty: 'General Surgery',
        specialties: [MedicalSpecialty.GENERAL_SURGERY],
        status: TheatreStatus.AVAILABLE,
        floor: '2nd Floor',
        room_number: 'OT-201',
        equipment: [
          { name: 'Anesthesia Machine', quantity: 1, status: 'available' },
          { name: 'Operating Table', quantity: 1, status: 'available' },
        ] as Equipment[],
        has_robotic_surgery: false,
        has_imaging: true,
        has_hybrid_capabilities: false,
        max_team_size: 8,
        sterility_class: SterilityClass.CLASS_B,
        total_surgeries: 120,
        average_turnover_time: 48,
        utilization_rate: 72,
      }),
      theatreRepo.create({
        hospital_id: hosp.id,
        name: `${hosp.name} - Emergency Theatre B`,
        type: TheatreType.EMERGENCY,
        specialty: 'Trauma Surgery',
        specialties: [MedicalSpecialty.ORTHOPEDICS, MedicalSpecialty.GENERAL_SURGERY],
        status: TheatreStatus.AVAILABLE,
        floor: '2nd Floor',
        room_number: 'OT-203',
        equipment: [
          { name: 'Ventilator', quantity: 1, status: 'available' },
          { name: 'Monitor', quantity: 2, status: 'available' },
        ] as Equipment[],
        has_robotic_surgery: false,
        has_imaging: true,
        has_hybrid_capabilities: true,
        max_team_size: 10,
        sterility_class: SterilityClass.CLASS_B,
        total_surgeries: 95,
        average_turnover_time: 42,
        utilization_rate: 79,
      }),
    ]);
  }

  console.log('Creating ambulances...');
  await ambulanceRepo.save([({
      vehicle_number: 'AMB-LAG-101',
      vehicle_make: 'Toyota',
      vehicle_model: 'Hiace',
      year: 2023,
      vin: 'JTF123456LAG101AA',
      hospital_id: hospitals[0].id,
      current_driver_id: lagosDriver.id,
      type: AmbulanceType.ALS,
      status: AmbulanceStatus.AVAILABLE,
      latitude: 6.5212,
      longitude: 3.3621,
      current_location: point(6.5212, 3.3621),
      available: true,
      has_life_support: true,
      capacity: 2,
      equipment: [
        { name: 'Defibrillator', quantity: 1, status: 'available' },
        { name: 'Portable Ventilator', quantity: 1, status: 'available' },
      ] as Equipment[],
      rating: 4.7,
      total_trips: 224,
    } as any),({
      vehicle_number: 'AMB-LAG-202',
      vehicle_make: 'Mercedes-Benz',
      vehicle_model: 'Sprinter',
      year: 2022,
      vin: 'WDB987654LAG202BB',
      hospital_id: hospitals[3].id,
      current_driver_id: lagosDriver.id,
      type: AmbulanceType.BLS,
      status: AmbulanceStatus.AVAILABLE,
      latitude: 6.4464,
      longitude: 3.4041,
      current_location: point(6.4464, 3.4041),
      available: true,
      has_life_support: false,
      capacity: 2,
      equipment: [
        { name: 'Oxygen Cylinder', quantity: 2, status: 'available' },
      ] as Equipment[],
      rating: 4.4,
      total_trips: 141,
    } as any),({
      vehicle_number: 'AMB-IBA-303',
      vehicle_make: 'Ford',
      vehicle_model: 'Transit',
      year: 2023,
      vin: 'FTR123777IBA303CC',
      hospital_id: hospitals[7].id,
      current_driver_id: ibadanDriver.id,
      type: AmbulanceType.ALS,
      status: AmbulanceStatus.AVAILABLE,
      latitude: 7.4022,
      longitude: 3.9022,
      current_location: point(7.4022, 3.9022),
      available: true,
      has_life_support: true,
      capacity: 2,
      equipment: [
        { name: 'Cardiac Monitor', quantity: 1, status: 'available' },
      ] as Equipment[],
      rating: 4.6,
      total_trips: 189,
    } as any),({
      vehicle_number: 'AMB-IBA-404',
      vehicle_make: 'Toyota',
      vehicle_model: 'Hiace',
      year: 2021,
      vin: 'TYT994422IBA404DD',
      hospital_id: hospitals[8].id,
      current_driver_id: ibadanDriver.id,
      type: AmbulanceType.BLS,
      status: AmbulanceStatus.AVAILABLE,
      latitude: 7.3871,
      longitude: 3.9031,
      current_location: point(7.3871, 3.9031),
      available: true,
      has_life_support: false,
      capacity: 2,
      equipment: [
        { name: 'First Aid Kit', quantity: 4, status: 'available' },
      ] as Equipment[],
      rating: 4.3,
      total_trips: 102,
    } as any),
  ]);

  console.log('Seed complete.');
  console.log('Login: admin@ambulance-theatre.com / Password123!');

  await AppDataSource.destroy();
}

seed().catch(async (err) => {
  console.error('Seed failed:', err);
  try {
    await AppDataSource.destroy();
  } catch {}
  process.exit(1);
});


